### ISSUE TITLE
Missing "datasets.py"

### ISSUE THREAD

**Issue by KunZhou9646** [ETZET/SpeechEmotionAVLearning#1]
Thanks for your sharing. Could you provide the missing file "datasets.py" that is used in data preparation?
![Screenshot 2024-03-12 at 4 45 47 PM](https://github.com/ETZET/SpeechEmotionAVLearning/assets/59918673/0cf7100d-d78b-42f4-a003-2a1807c28a20)

**Comment by tianqingzhou** [comment]
I hope this email finds you well.

I recently ran the code file "wavLM" and noticed that it completed execution without generating the expected "embedding.pickle" file. Additionally, the achieved accuracy was only around 0.06.

Could you please provide some insights or guidance on why this might have occurred? I would appreciate any suggestions or assistance you can offer in troubleshooting this issue.

Thank you for your attention to this matter.

**Comment by ETZET** [comment]
Hi tianqingzhou,

Thanks for your interest in the code. What data are you using? Are you also using IEMOCAP? If so, please run the preprocessing script in data_prep/data_prep/IEMOCAP_preprocess.py. Can you also confirm that the sampling rate is 16000?

After training, you main use the inference mode to generate the embedding.pickle. Please modify how to generate that file according your data .(Line 271 and line 341 in wavlm.py)

Hope these helps.
Enting
________________________________
发件人: tianqingzhou ***@***.***>
发送时间: 2024年4月17日 15:43
收件人: ETZET/SpeechEmotionAVLearning ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ETZET/SpeechEmotionAVLearning] Missing "datasets.py" (Issue #1)


I hope this email finds you well.

I recently ran the code file "wavLM" and noticed that it completed execution without generating the expected "embedding.pickle" file. Additionally, the achieved accuracy was only around 0.06.

Could you please provide some insights or guidance on why this might have occurred? I would appreciate any suggestions or assistance you can offer in troubleshooting this issue.

Thank you for your attention to this matter.

―

**Comment by tqzhou75** [comment]
/dataHDD/ezhou12/dump/crema/model_epoch_20.pth

**Comment by tqzhou75** [comment]
I am writing to kindly ask if you could share the files from the following two directories:
/home/enting/Documents/EmoDR/dump/iemocap_baseline_partial/model_last_epoch.pth
/dataHDD/ezhou12/dump/crema/model_epoch_20.pth Thank you very much for your help.
